# Generated by Django 3.2.9 on 2021-12-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperLeague', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
