# Generated by Django 3.2.9 on 2021-12-05 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperLeague', '0002_tour_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='is_done',
        ),
        migrations.AlterField(
            model_name='tour',
            name='goal_away',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='goal_home',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Turnament_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.IntegerField(default=38)),
                ('goal_difference', models.IntegerField()),
                ('points', models.IntegerField()),
                ('clubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club', to='SuperLeague.club')),
            ],
        ),
    ]
