# Generated by Django 3.2.9 on 2021-12-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperLeague', '0003_auto_20211205_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnament_table',
            name='clubs',
            field=models.CharField(max_length=50),
        ),
    ]
