# Generated by Django 3.2.9 on 2021-12-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperLeague', '0004_alter_turnament_table_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tour',
            name='goal_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tour',
            name='goal_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='turnament_table',
            name='goal_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='turnament_table',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
