# Generated by Django 3.2.9 on 2021-12-07 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperLeague', '0005_auto_20211207_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnament_table',
            name='clubs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs_name', to='SuperLeague.club'),
        ),
        migrations.AlterField(
            model_name='turnament_table',
            name='matches',
            field=models.IntegerField(default=0),
        ),
    ]
