# Generated by Django 3.2.9 on 2021-12-08 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperLeague', '0006_auto_20211207_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnament_table',
            name='id',
        ),
        migrations.AlterField(
            model_name='turnament_table',
            name='clubs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SuperLeague.club'),
        ),
    ]
