# Generated by Django 3.2.9 on 2021-12-08 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperLeague', '0007_auto_20211208_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnament_table',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turnament_table',
            name='clubs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs_id', to='SuperLeague.club'),
        ),
    ]
